version: '3.8'

services:
  # Ollama service
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 8G
    restart: unless-stopped
    networks:
      - ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Streamlit web app
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    container_name: product-advisor-webapp
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - ai-network

volumes:
  ollama-data:
    driver: local

networks:
  ai-network:
    driver: bridge

